(function(){'use strict';
const cfg=window.APP_CONFIG||{};let catalog=null,records=[],view=[];const $=id=>document.getElementById(id);const labels={TOTAL_CARTERA:'Total Cartera',NO_DEVENGA:'No Devenga',CARTERA_VENCIDA_60:'Cartera Vencida +60',NO_DEVENGA_MAS_90:'No Devenga +90',CARTERA_CASTIGADA:'Cartera Castigada'};const colors={CTH:'#173f5f',F8:'#2f80ed',F11:'#27ae60',F12:'#eb5757'};
document.addEventListener('DOMContentLoaded',init);
async function init(){try{const [c,s,o]=await Promise.all([fetch(cfg.historicalCatalogUrl||'data/historico/catalogo.json').then(r=>r.json()),fetch(cfg.historicalSeriesUrl||'data/historico/series.json').then(r=>r.json()),fetch('data/operational/catalog.json',{cache:'no-store'}).then(r=>r.ok?r.json():({records:[]})).catch(()=>({records:[]}))]);catalog=c;const merged=new Map();(s.records||[]).forEach(r=>merged.set(`${r.period}|${r.company}`,r));(o.records||[]).forEach(r=>merged.set(`${r.period}|${r.company}`,r));records=[...merged.values()];const ps=[...new Set(records.map(r=>r.period))].sort();catalog.periods=ps;catalog.periodStart=ps[0];catalog.periodEnd=ps[ps.length-1];catalog.periodCount=ps.length;catalog.companyPeriodCount=records.length;fillPeriods();$('openDrive').href=cfg.driveHistoricalFolderUrl||'#';bind();apply();$('coverageBadge').textContent=`${catalog.periodCount} períodos · ${catalog.companyPeriodCount} registros empresa/mes`;}catch(e){$('coverageBadge').textContent='No se pudo cargar el histórico';console.error(e);}}
function bind(){$('applyFilters').onclick=apply;$('downloadExcel').onclick=exportExcel;$('downloadPdf').onclick=exportPdf;$('comparisonType').onchange=()=>{$('fromPeriod').disabled=$('toPeriod').disabled=$('comparisonType').value!=='CUSTOM';};}
function fillPeriods(){const ps=[...catalog.periods].reverse();['basePeriod','fromPeriod','toPeriod'].forEach(id=>{const el=$(id);el.innerHTML=ps.map(p=>`<option value="${p}">${periodLabel(p)}</option>`).join('');});$('basePeriod').value=catalog.periodEnd;$('toPeriod').value=catalog.periodEnd;$('fromPeriod').value=catalog.periods[Math.max(0,catalog.periods.length-12)];}
function selectedCompanies(){return [...$('companyFilter').selectedOptions].map(o=>o.value);}
function periodLabel(p){const [y,m]=p.split('-').map(Number);return new Intl.DateTimeFormat('es-EC',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(Date.UTC(y,m-1,1))).replace(/^./,x=>x.toUpperCase());}
function previousPeriod(p,n=1){let[y,m]=p.split('-').map(Number);m-=n;while(m<=0){m+=12;y--;}return `${y}-${String(m).padStart(2,'0')}`;}
function comparisonPeriods(base,type){if(type==='YOY')return[previousPeriod(base,12),base];if(type==='CUSTOM'){const a=$('fromPeriod').value,b=$('toPeriod').value;return catalog.periods.filter(p=>p>=a&&p<=b);}const n=Number(type.replace('PREV',''))||3;const start=previousPeriod(base,n);return catalog.periods.filter(p=>p>=start&&p<=base);}
function metric(rec,key){return rec&&rec.metrics&&rec.metrics[key]?rec.metrics[key].valueThousands:null;}function ops(rec){return rec&&rec.metrics&&rec.metrics.TOTAL_CARTERA?rec.metrics.TOTAL_CARTERA.operations:null;}function rec(period,company){return records.find(r=>r.period===period&&r.company===company);}
function pct(a,b){return a==null||b==null||b===0?null:(a-b)/b;}function fmt(v){return v==null?'—':Math.round(v).toLocaleString('es-EC');}function fmtPct(v){return v==null?'—':`${v>=0?'+':''}${Math.round(v*100)}%`;}
function apply(){if(!catalog)return;const cs=selectedCompanies();const base=$('basePeriod').value;const periods=comparisonPeriods(base,$('comparisonType').value);view=records.filter(r=>cs.includes(r.company)&&periods.includes(r.period));$('analysisTitle').textContent=`${labels[$('metricFilter').value]} · ${periodLabel(base)}`;$('analysisSubtitle').textContent=`Comparación de ${cs.join(', ')} en ${periods.length} período(s).`;renderKpis(base,cs);renderLine(periods,cs);renderBars(base,cs);renderTable(periods,cs);renderAlerts(base,cs);renderRanking(base,cs);$('sourceLegend').textContent='Fuente: histórico consolidado normalizado';}
function aggregate(period,cs,key){const vals=cs.map(c=>metric(rec(period,c),key)).filter(v=>v!=null);return vals.length?vals.reduce((a,b)=>a+b,0):null;}function aggregateOps(period,cs){const vals=cs.map(c=>ops(rec(period,c))).filter(v=>v!=null);return vals.length?vals.reduce((a,b)=>a+b,0):null;}
function renderKpis(base,cs){const prev=previousPeriod(base),yoy=previousPeriod(base,12);const items=[['Total cartera','TOTAL_CARTERA'],['Operaciones','OPS'],['Cartera vencida','CARTERA_VENCIDA_60'],['No Devenga','NO_DEVENGA'],['No Devenga +90','NO_DEVENGA_MAS_90']];$('historyKpis').innerHTML=items.map(([name,key])=>{const v=key==='OPS'?aggregateOps(base,cs):aggregate(base,cs,key);const pv=key==='OPS'?aggregateOps(prev,cs):aggregate(prev,cs,key);const yv=key==='OPS'?aggregateOps(yoy,cs):aggregate(yoy,cs,key);const d=pct(v,pv),dy=pct(v,yv);return`<article class="history-kpi"><span>${name}</span><strong>${fmt(v)}</strong><small class="${d>0?'delta-up':'delta-down'}">Mensual ${fmtPct(d)}</small><small> · Interanual ${fmtPct(dy)}</small></article>`;}).join('');}
function renderLine(periods,cs){const key=$('metricFilter').value;const W=900,H=320,pad={l:55,r:20,t:25,b:48};const series=cs.map(c=>({c,vals:periods.map(p=>metric(rec(p,c),key))}));const all=series.flatMap(s=>s.vals).filter(v=>v!=null);if(!all.length){$('lineChart').innerHTML='<p>Sin información.</p>';return;}const min=Math.min(...all),max=Math.max(...all),span=max-min||1;const x=i=>pad.l+i*(W-pad.l-pad.r)/Math.max(1,periods.length-1),y=v=>pad.t+(max-v)*(H-pad.t-pad.b)/span;let svg=`<svg viewBox="0 0 ${W} ${H}" role="img">`;for(let i=0;i<5;i++){const yy=pad.t+i*(H-pad.t-pad.b)/4;const val=max-i*span/4;svg+=`<line class="chart-grid" x1="${pad.l}" y1="${yy}" x2="${W-pad.r}" y2="${yy}"/><text class="chart-axis" x="4" y="${yy+4}">${fmt(val)}</text>`;}series.forEach(s=>{let d='';s.vals.forEach((v,i)=>{if(v==null)return;d+=`${d?'L':'M'}${x(i)},${y(v)} `;});svg+=`<path class="chart-line" stroke="${colors[s.c]}" d="${d}"/>`;s.vals.forEach((v,i)=>{if(v!=null)svg+=`<circle class="chart-point" fill="${colors[s.c]}" cx="${x(i)}" cy="${y(v)}" r="4"/>`;});});const step=Math.max(1,Math.ceil(periods.length/8));periods.forEach((p,i)=>{if(i%step===0||i===periods.length-1)svg+=`<text class="chart-axis" text-anchor="middle" x="${x(i)}" y="${H-18}">${p}</text>`;});svg+='</svg><div class="legend">'+cs.map(c=>`<span><i style="background:${colors[c]}"></i>${c}</span>`).join('')+'</div>';$('lineChart').innerHTML=svg;}
function renderBars(base,cs){const key=$('metricFilter').value;const vals=cs.map(c=>({c,v:metric(rec(base,c),key)||0}));const max=Math.max(...vals.map(x=>x.v),1),W=520,H=320,p={l:55,r:20,t:30,b:45},bw=(W-p.l-p.r)/Math.max(1,vals.length);let svg=`<svg viewBox="0 0 ${W} ${H}">`;vals.forEach((o,i)=>{const h=o.v/max*(H-p.t-p.b),xx=p.l+i*bw+15,yy=H-p.b-h;svg+=`<rect x="${xx}" y="${yy}" width="${Math.max(22,bw-30)}" height="${h}" rx="7" fill="${colors[o.c]}"/><text class="chart-axis" text-anchor="middle" x="${xx+Math.max(22,bw-30)/2}" y="${H-20}">${o.c}</text><text class="chart-axis" text-anchor="middle" x="${xx+Math.max(22,bw-30)/2}" y="${Math.max(16,yy-7)}">${fmt(o.v)}</text>`;});svg+='</svg>';$('barChart').innerHTML=svg;}
function renderTable(periods,cs){const rows=[];[...periods].reverse().forEach(p=>cs.forEach(c=>{const r=rec(p,c);if(!r)return;const total=metric(r,'TOTAL_CARTERA'),prev=metric(rec(previousPeriod(p),c),'TOTAL_CARTERA'),yoy=metric(rec(previousPeriod(p,12),c),'TOTAL_CARTERA');rows.push(`<tr><td>${periodLabel(p)}</td><td><strong>${c}</strong></td><td>${fmt(total)}</td><td>${fmt(ops(r))}</td><td>${fmt(metric(r,'CARTERA_VENCIDA_60'))}</td><td>${fmt(metric(r,'NO_DEVENGA'))}</td><td>${fmt(metric(r,'NO_DEVENGA_MAS_90'))}</td><td>${fmtPct(pct(total,prev))}</td><td>${fmtPct(pct(total,yoy))}</td><td>${r.sourcePath?`<a class="source-chip" href="${r.sourcePath}" download>GitHub</a>`:`<a class="source-chip" href="${cfg.driveHistoricalFolderUrl||'#'}" target="_blank" rel="noopener">Drive ${r.sourcePeriod}</a>`}</td></tr>`);}));$('historyTableBody').innerHTML=rows.join('')||'<tr><td colspan="10">Sin información.</td></tr>';}
function renderAlerts(base,cs){const th=Number($('alertThreshold').value||10)/100;const list=[];cs.forEach(c=>{['TOTAL_CARTERA','NO_DEVENGA','CARTERA_VENCIDA_60','NO_DEVENGA_MAS_90'].forEach(k=>{const v=metric(rec(base,c),k),p=metric(rec(previousPeriod(base),c),k),d=pct(v,p);if(d!=null&&Math.abs(d)>=th)list.push({c,k,d});});});$('alertsList').innerHTML=list.length?list.sort((a,b)=>Math.abs(b.d)-Math.abs(a.d)).map(x=>`<div class="alert-item"><span><strong>${x.c}</strong><br><small>${labels[x.k]||x.k}</small></span><strong class="${x.d>0?'delta-up':'delta-down'}">${fmtPct(x.d)}</strong></div>`).join(''):'<div class="alert-item">No existen desviaciones superiores al umbral.</div>';}
function renderRanking(base,cs){const key=$('metricFilter').value;const rows=cs.map(c=>({c,v:metric(rec(base,c),key)})).filter(x=>x.v!=null).sort((a,b)=>b.v-a.v);$('rankingList').innerHTML=rows.map((x,i)=>`<div class="rank-item"><span><strong>${i+1}. ${x.c}</strong><br><small>${labels[key]}</small></span><strong>${fmt(x.v)}</strong></div>`).join('');}
async function exportExcel(){if(!view.length)return;const rows=[['Período','Empresa','Total Cartera','Operaciones','Cartera Vencida +60','No Devenga','No Devenga +90','Fuente']];view.sort((a,b)=>a.period.localeCompare(b.period)||a.company.localeCompare(b.company)).forEach(r=>rows.push([r.period,r.company,metric(r,'TOTAL_CARTERA'),ops(r),metric(r,'CARTERA_VENCIDA_60'),metric(r,'NO_DEVENGA'),metric(r,'NO_DEVENGA_MAS_90'),r.source]));const blob=await simpleXlsx(rows);download(blob,`Historico_Cartera_${$('basePeriod').value}.xlsx`);}
async function simpleXlsx(rows){const z=new JSZip(),esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');const cols=n=>{let s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26);}return s;};let xml='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>';rows.forEach((row,ri)=>{xml+=`<row r="${ri+1}">`;row.forEach((v,ci)=>{const ref=cols(ci+1)+(ri+1);if(typeof v==='number')xml+=`<c r="${ref}"><v>${v}</v></c>`;else xml+=`<c r="${ref}" t="inlineStr"><is><t>${esc(v)}</t></is></c>`;});xml+='</row>';});xml+='</sheetData></worksheet>';z.file('[Content_Types].xml','<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>');z.file('_rels/.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');z.file('xl/workbook.xml','<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Comparativo" sheetId="1" r:id="rId1"/></sheets></workbook>');z.file('xl/_rels/workbook.xml.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>');z.file('xl/worksheets/sheet1.xml',xml);return z.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});}
function exportPdf(){if(!window.jspdf)return alert('El motor PDF no está disponible.');const {jsPDF}=window.jspdf,doc=new jsPDF({orientation:'landscape'});doc.setFontSize(18);doc.text('CTH · Análisis histórico de cartera',14,18);doc.setFontSize(10);doc.text(`${$('analysisTitle').textContent} · Valores en miles de USD`,14,26);const body=[...$('historyTableBody').querySelectorAll('tr')].map(tr=>[...tr.cells].slice(0,9).map(td=>td.innerText));doc.autoTable({startY:32,head:[['Período','Empresa','Total','Oper.','Vencida','No Devenga','ND +90','Var. mensual','Var. interanual']],body,styles:{fontSize:7},headStyles:{fillColor:[23,63,95]}});doc.save(`Historico_Cartera_${$('basePeriod').value}.pdf`);}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
})();
